name: Hebi's Blog
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
paginate: 5
# excerpt_separator: <!--more-->
